version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-postgres

networks:
  node-postgres:

volumes:
  pgdata:
