services:
  postgres:
    image: pgvector/pgvector:0.7.0-pg15  # ✅ pgvector with Postgres 15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: courseai
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/seeds:/docker-entrypoint-initdb.d/seeds:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d courseai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - courseai-network

  postgres-shadow:
    image: pgvector/pgvector:0.7.0-pg15  # ✅ pgvector for shadow DB
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prisma_shadow
    volumes:
      - pgdata_shadow:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - courseai-network

volumes:
  pgdata:
  pgdata_shadow:

networks:
  courseai-network:
    name: courseai-network
    driver: bridge