services:
  - type: web
    name: nextjs-app
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm start # or yarn start if you use Yarn
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: build-cache
      mountPath: /cache
      sizeGB: 2
    build:
      cacheDirs:
        - /cache/node_modules
        - /cache/.next/cache
