import { Code, PenTool, Flashlight, BookOpen, Target } from "lucide-react"

export const QUIZ_TYPE_CONFIG = {
  mcq: {
    label: "Multiple Choice",
    icon: Target,
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-950/30",
    border: "border-blue-200 dark:border-blue-800",
    pill: "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    gradient: "from-blue-500/10 to-blue-600/5",
    accent: "bg-blue-500",
  },
  code: {
    label: "Code Challenge",
    icon: Code,
    color: "text-green-600 dark:text-green-400",
    bg: "bg-green-50 dark:bg-green-950/30",
    border: "border-green-200 dark:border-green-800",
    pill: "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300 border-green-200 dark:border-green-800",
    gradient: "from-green-500/10 to-green-600/5",
    accent: "bg-green-500",
  },
  flashcard: {
    label: "Flashcards",
    icon: Flashlight,
    color: "text-yellow-600 dark:text-yellow-400",
    bg: "bg-yellow-50 dark:bg-yellow-950/30",
    border: "border-yellow-200 dark:border-yellow-800",
    pill: "bg-yellow-100 dark:bg-yellow-900/40 text-yellow-700 dark:text-yellow-300 border-yellow-200 dark:border-yellow-800",
    gradient: "from-yellow-500/10 to-yellow-600/5",
    accent: "bg-yellow-500",
  },
  openended: {
    label: "Open Ended",
    icon: PenTool,
    color: "text-[hsl(var(--primary))] dark:text-[hsl(var(--primary))]",
    bg: "bg-[hsl(var(--primary))]/10 dark:bg-[hsl(var(--primary))]/20",
    border: "border-[hsl(var(--primary))]/30 dark:border-[hsl(var(--primary))]/40",
    pill: "bg-[hsl(var(--primary))]/15 dark:bg-[hsl(var(--primary))]/25 text-[hsl(var(--primary))] dark:text-[hsl(var(--primary))] border-[hsl(var(--primary))]/30 dark:border-[hsl(var(--primary))]/40",
    gradient: "from-[hsl(var(--primary))]/10 to-[hsl(var(--primary))]/5",
    accent: "bg-[hsl(var(--primary))]",
  },
  blanks: {
    label: "Fill in Blanks",
    icon: BookOpen,
    color: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-50 dark:bg-orange-950/30",
    border: "border-orange-200 dark:border-orange-800",
    pill: "bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300 border-orange-200 dark:border-orange-800",
    gradient: "from-orange-500/10 to-orange-600/5",
    accent: "bg-orange-500",
  },
} as const
