#!/bin/bash
set -e

ARCHIVE_DIR="archive2"
LOG_FILE="manual-archive2-log.txt"

# List of files to archive (from user's selection)
FILES_TO_ARCHIVE=(
"archive/chatgpt-backup-20251020/chatgpt/ai-service.ts"
"archive/chatgpt-backup-20251020/chatgpt/chatGptRequest.ts"
"archive/chatgpt-backup-20251020/chatgpt/enerateSummaryGPT.ts"
"archive/chatgpt-backup-20251020/chatgpt/generateCourseContent.ts"
"archive/chatgpt-backup-20251020/chatgpt/generateQuestions.ts"
"archive/chatgpt-backup-20251020/chatgpt/openaiUtils.ts"
"archive/chatgpt-backup-20251020/chatgpt/summaryGenerator.ts"
"archive/chatgpt-backup-20251020/chatgpt/userMcqQuiz.ts"
"archive/chatgpt-backup-20251020/chatgpt/videoQuiz.ts"
"components/course/utils/formatUtils.ts"
"components/features/chat/Chatbot.tsx"
"components/features/courses/index.ts"
"components/features/dashboard/index.ts"
"components/features/dashboard/Recommendations.tsx"
"components/features/home/CategoryTagCloud.tsx"
"components/features/home/CourseListSkeleton.tsx"
"components/features/home/CourseListWithFilters.v2.tsx"
"components/features/home/CoursesClient.tsx"
"components/features/home/CourseSidebar.tsx"
"components/features/quizzes/HelpModal.tsx"
"components/features/quizzes/index.ts"
"components/features/subscription/ImprovedAuthDialog.tsx"
"components/features/subscription/index.ts"
"components/features/user/UserProfile.tsx"
"components/landing/sections/AppleStyleParticles.tsx"
"components/landing/sections/CTASection.tsx"
"components/landing/sections/ShowCase.tsx"
"components/landing/sections/TeamIllustration.tsx"
"components/landing/sections/VideoSection.tsx"
"components/landing/skeletons/FeaturesSkeleton.tsx"
"components/landing/svg/CTASVG.tsx"
"components/landing/svg/FeaturesSVG.tsx"
"components/landing/svg/HeroSVG.tsx"
"components/landing/svg/HowItWorksSVG.tsx"
"components/landing/svg/RevealAnimation.tsx"
"components/landing/svg/ValueIcon.tsx"
"components/quiz/shared/index.tsx"
"components/ui/animations/animation-toggle.tsx"
"components/ui/animations/hover-animation.tsx"
"components/ui/animations/index.tsx"
"components/ui/animations/motion-preset.tsx"
"components/ui/animations/motion-wrapper.tsx"
"components/ui/animations/reveal-image.tsx"
"components/ui/animations/scroll-animation.tsx"
"components/ui/animations/staggered-list.tsx"
"lib/ai/prompts/index.ts"
"lib/ai/services/course-outline-generator.ts"
"lib/ai/services/wrappers.ts"
"store/slices/quiz/quiz-slice-types.ts"
"app/api/course/[slug]/chapter.ts"
"app/auth/signin/components/AppleStyleParticles.tsx"
"app/auth/signin/components/AuthButtons.tsx"
"app/auth/signin/components/AuthGuard.tsx"
"app/auth/signin/components/AuthStatus.tsx"
"app/auth/signin/components/AuthStatusIndicator.tsx"
"app/dashboard/(quiz)/components/AIQuizNoticeModal.tsx"
"app/dashboard/(quiz)/components/BaseQuizResult.tsx"
"app/dashboard/(quiz)/components/QuestionNavigation.tsx"
"app/dashboard/(quiz)/components/quiz-result-types.ts"
"app/dashboard/(quiz)/components/QuizLoadingSkeleton.tsx"
"app/dashboard/(quiz)/components/text-similarty.tsx"
"app/dashboard/(quiz)/components/types.ts"
"app/dashboard/(quiz)/components/utils.ts"
"app/dashboard/(quiz)/services/quiz-api-client.ts"
"app/dashboard/(quiz)/utils/quiz-result-utils.ts"
"app/dashboard/cancelled/components/CancelledContent.tsx"
"app/dashboard/create/components/ChapterCard.tsx"
"app/dashboard/create/components/ChapterCardHandler.tsx"
"app/dashboard/create/components/ConfigurableQuizPDF.tsx"
"app/dashboard/create/components/ConfirmChapters.tsx"
"app/dashboard/create/components/DragDropHelpModal.tsx"
"app/dashboard/create/components/DragDropTutorial.tsx"
"app/dashboard/create/components/QuizPdfButton.tsx"
"app/dashboard/create/components/StepIndicator.tsx"
"app/dashboard/create/components/UnauthenticatedContent.tsx"
"app/dashboard/create/components/UnitCard.tsx"
"app/dashboard/create/hooks/useChapterProcessing.ts"
"app/dashboard/create/services/courseService.ts"
"app/dashboard/home/components/LearningActivity.tsx"
"app/dashboard/home/components/MyCourses.tsx"
"app/dashboard/home/components/MyQuizzes.tsx"
"app/dashboard/home/components/ProgressOverview.tsx"
"app/dashboard/home/components/QuickOverview.tsx"
"app/dashboard/home/components/QuizAttempts.tsx"
"app/dashboard/home/components/QuizHistory.tsx"
"app/dashboard/home/components/QuizPerformance.tsx"
"app/dashboard/home/components/RecentQuizCard.tsx"
"app/dashboard/home/components/StatsTab.tsx"
"app/dashboard/home/components/UnfinishedQuizzes.tsx"
"app/dashboard/home/components/UserStatsOverview.tsx"
"app/dashboard/subscription/components/subscription-status.tsx"
"app/dashboard/subscription/services/enhanced-stripe-gateway.ts"
"app/dashboard/subscription/utils/feature-utils.ts"
"app/dashboard/subscription/utils/validation.ts"
"app/dashboard/(quiz)/blanks/components/types.ts"
"app/dashboard/(quiz)/code/components/CodeQuizEditor.tsx"
"app/dashboard/(quiz)/code/components/CodeQuizOptions.tsx"
"app/dashboard/(quiz)/code/components/CodeQuizResult.tsx"
"app/dashboard/(quiz)/document/components/KeyboardShortcuts.tsx"
"app/dashboard/(quiz)/mcq/components/LearningInsights.tsx"
"app/dashboard/(quiz)/mcq/components/McqQuizResult.tsx"
"app/dashboard/(quiz)/quizzes/components/LoadingCard.tsx"
"app/dashboard/(quiz)/quizzes/components/quizTypeConfig.ts"
"app/dashboard/(quiz)/quizzes/components/SearchBar.tsx"
"app/dashboard/(quiz)/ordering/components/OrderingQuizResults.tsx"
"app/dashboard/(quiz)/ordering/[slug]/OrderingQuizClient.tsx"
"app/dashboard/admin/components/user-dialog/user-edit-dialog.tsx"
"app/dashboard/admin/components/user-management/user-management-context.tsx"
"app/dashboard/course/[slug]/components/AuthPrompt.tsx"
"app/dashboard/course/[slug]/components/CourseActions.tsx"
"app/dashboard/course/[slug]/components/CourseErrorBoundary.tsx"
"app/dashboard/course/[slug]/components/CourseHeader.tsx"
"app/dashboard/course/[slug]/components/CourseInfo.tsx"
"app/dashboard/course/[slug]/components/CourseInfoSidebar.tsx"
"app/dashboard/course/[slug]/components/CourseProgressHeader.tsx"
"app/dashboard/course/[slug]/components/EngagementPrompts.tsx"
"app/dashboard/course/[slug]/components/index.ts"
"app/dashboard/course/[slug]/components/MobilePlaylistToggle.tsx"
"app/dashboard/course/[slug]/components/VideoSection.tsx"
"app/dashboard/course/[slug]/hooks/useAutoplay.ts"
"app/dashboard/course/[slug]/hooks/useKeyboardShortcuts.ts"
"app/dashboard/course/[slug]/hooks/useLayoutManagement.ts"
"app/dashboard/course/[slug]/hooks/useVideoManagement.ts"
"app/dashboard/course/[slug]/utils/chapterCompletion.ts"
"app/dashboard/course/[slug]/utils/courseUtils.ts"
"app/dashboard/course/[slug]/utils/videoUtils.ts"
"app/dashboard/subscription/components/subscription-status/ComparisonTable.tsx"
"app/dashboard/subscription/components/subscription-status/FaqSection.tsx"
"app/dashboard/subscription/components/subscription-status/TokenUsageExplanation.tsx"
"app/dashboard/(quiz)/ordering/[slug]/components/OrderingQuiz.tsx"
"app/dashboard/course/[slug]/components/modals/BookmarkModal.tsx"
"app/dashboard/course/[slug]/components/video/index.tsx"
"app/dashboard/course/[slug]/components/video/VideoErrorState.tsx"
"app/dashboard/course/[slug]/components/video/hooks/useOfflineDetection.ts"
"app/dashboard/course/[slug]/components/video/hooks/zustandUtils.ts"
"app/dashboard/course/[slug]/components/video/components/BookmarkTimeline.tsx"
"app/dashboard/course/[slug]/components/video/components/NextChapterAutoOverlay.tsx"
"app/dashboard/course/[slug]/components/video/components/ProgressBar.tsx"
"app/dashboard/course/[slug]/components/video/components/VideoLoadingOverlay.tsx"
)

echo "🚚 Archiving specified unused files to: $ARCHIVE_DIR"
mkdir -p "$ARCHIVE_DIR"

COUNT=0
for FILE in "${FILES_TO_ARCHIVE[@]}"; do
  if [ -f "$FILE" ]; then
    DEST="$ARCHIVE_DIR/$FILE"
    mkdir -p "$(dirname "$DEST")"
    mv "$FILE" "$DEST"
    echo "📦 Moved: $FILE → $DEST"
    echo "$FILE" >> "$LOG_FILE"
    COUNT=$((COUNT+1))
  else
    echo "⚠️  File not found: $FILE"
  fi
done

echo "✅ Total archived: $COUNT"
echo "📝 Log saved to $LOG_FILE"