"use client"

import { useState, useRef, useEffect } from "react"
import { motion, AnimatePresence, useInView } from "framer-motion"
import { Search, HelpCircle } from "lucide-react"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"

const faqData = [
  {
    question: "How does Course AI create personalized learning paths?",
    answer:
      "Course AI employs sophisticated algorithms to analyze user input, specifically focusing on topics and subtopics of interest. Using this analysis, it generates custom course content designed around the specified topic and subtopic, ensuring each user receives personalized course material tailored to their unique learning needs.",
  },
  {
    question: "What are auto-knowledge checks?",
    answer:
      "Auto-knowledge checks are interactive features integrated into our platform to assess users' comprehension of course materials. They present quiz questions or interactive exercises strategically throughout a course, helping reinforce learning and identify areas for improvement.",
  },
  {
    question: "How do I address errors encountered with Course AI?",
    answer:
      "If you encounter errors while using Course AI, please report them via our contact page. Factors contributing to errors may include data inconsistencies, algorithm limitations, or technical issues. Our team will investigate promptly to ensure a seamless learning experience.",
  },
  {
    question: "Where are the videos hosted, and can I view public courses?",
    answer:
      "Our platform utilizes YouTube videos for course content. Public courses can be accessed by anyone with the appropriate course link. However, certain premium features may require registration or a subscription.",
  },
  {
    question: "Are there limitations on the number of courses I can create?",
    answer:
      "With the Free plan, you receive 3 tokens upon registration, which can be used to create up to 3 courses. To access additional course creation features, consider upgrading to one of our premium plans.",
  },
  {
    question: "What if course generation failed?",
    answer:
      "If course generation fails, you can view your account to see the failed course and attempt to regenerate it. If issues persist, contact our support team for assistance.",
  },
  {
    question: "Are all courses generated by default public?",
    answer:
      "Yes, by default, all courses generated are public. However, you have the option to make them private if needed.",
  },
  {
    question: "Can I delete a course?",
    answer:
      "Yes, you can delete a course if you are the owner. Course management options are available in the course details section, including the ability to make a course private or delete it.",
  },
  {
    question: "How does your pricing model work?",
    answer:
      "We offer tiered pricing based on features and usage. Our Free plan includes 3 tokens for course creation, while paid plans unlock additional features and higher limits. Visit our pricing page for detailed information.",
  },
  {
    question: "How secure is my course content on your platform?",
    answer:
      "We prioritize the security and privacy of your data. All content is encrypted in transit and at rest using industry-standard protocols. Additionally, your content remains your intellectual property, and we do not share it without your consent.",
  },
  {
    question: "What are the terms of service and privacy policy?",
    answer:
      "By using our platform, you agree to our terms of service and privacy policy. These documents outline your rights, obligations, and data usage policies. Please review them on our website to ensure you are informed.",
  },
  {
    question: "Are there any disclaimers I should be aware of?",
    answer:
      "Our platform is designed to assist with educational content creation, but we do not guarantee the accuracy or completeness of generated materials. Users are advised to review and verify all course content before use.",
  },
  {
    question: "Does the video transcript always generate?",
    answer:
      "No, our platform uses YouTube. If a video transcript is available, only then can our platform generate a summary and quiz.",
  },
]

export default function FAQSection() {
  const [searchTerm, setSearchTerm] = useState("")
  const [expandedItem, setExpandedItem] = useState<string | null>(null)
  const [highlightedTerms, setHighlightedTerms] = useState<string[]>([])
  const sectionRef = useRef(null)
  const isInView = useInView(sectionRef, { once: true, amount: 0.2 })
  const searchInputRef = useRef<HTMLInputElement>(null)

  const filteredFAQs = faqData.filter(
    (faq) =>
      faq.question?.toLowerCase().includes(searchTerm?.toLowerCase()) ||
      faq.answer?.toLowerCase().includes(searchTerm?.toLowerCase()),
  )

  useEffect(() => {
    if (searchTerm) {
      setHighlightedTerms(
        searchTerm
          ?.toLowerCase()
          .split(" ")
          .filter((term) => term.length > 2),
      )
    } else {
      setHighlightedTerms([])
    }
  }, [searchTerm])

  // Auto-focus search input when section comes into view
  useEffect(() => {
    if (isInView && searchInputRef.current) {
      setTimeout(() => {
        searchInputRef.current?.focus()
      }, 500)
    }
  }, [isInView])

  // Highlight matching text
  const highlightText = (text: string) => {
    if (highlightedTerms.length === 0) return text

    let highlightedText = text
    highlightedTerms.forEach((term) => {
      const regex = new RegExp(`(${term})`, "gi")
      highlightedText = highlightedText.replace(
        regex,
        '<mark class="bg-primary/20 text-foreground px-1 rounded">$1</mark>',
      )
    })

    return <span dangerouslySetInnerHTML={{ __html: highlightedText }} />
  }

  return (
    <section ref={sectionRef} className="py-10 md:py-16 bg-gradient-to-b from-background to-secondary/20">
      <div className="container px-4 md:px-6 max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          className="space-y-8"
        >
          <motion.div
            className="relative mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
            <Input
              ref={searchInputRef}
              type="text"
              placeholder="Search FAQs..."
              className="pl-10 w-full bg-background border-border focus:ring-2 focus:ring-primary/30 transition-all duration-300"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            {searchTerm && (
              <motion.button
                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground hover:text-foreground"
                onClick={() => setSearchTerm("")}
                initial={{ opacity: 0, scale: 0 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0 }}
                whileHover={{ rotate: 90 }}
                transition={{ duration: 0.2 }}
              >
                ✕
              </motion.button>
            )}
          </motion.div>

          <AnimatePresence mode="wait">
            {filteredFAQs.length > 0 ? (
              <motion.div
                key="faq-list"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.3 }}
              >
                <Accordion
                  type="single"
                  collapsible
                  className="w-full space-y-4"
                  value={expandedItem || undefined}
                  onValueChange={setExpandedItem}
                >
                  {filteredFAQs.map((item, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.3, delay: index * 0.05 }}
                    >
                      <AccordionItem
                        value={`item-${index}`}
                        className={cn(
                          "border rounded-lg overflow-hidden",
                          "transition-all duration-200 ease-in-out",
                          "hover:shadow-md",
                          expandedItem === `item-${index}` && "shadow-md border-primary/50",
                        )}
                      >
                        <AccordionTrigger
                          className={cn(
                            "px-5 py-4 flex items-center justify-between text-left bg-card hover:bg-muted/50 transition-colors duration-200",
                            expandedItem === `item-${index}` && "bg-muted/30",
                          )}
                        >
                          <div className="flex items-center space-x-3">
                            <motion.div
                              animate={
                                expandedItem === `item-${index}`
                                  ? {
                                      rotate: [0, 15, 0, -15, 0],
                                      scale: [1, 1.2, 1],
                                      color: ["hsl(var(--primary))", "hsl(var(--primary))", "hsl(var(--primary))"],
                                    }
                                  : {}
                              }
                              transition={{ duration: 0.5 }}
                            >
                              <HelpCircle className="flex-shrink-0 w-5 h-5 text-primary" />
                            </motion.div>
                            <span className="text-base font-medium text-foreground">
                              {highlightText(item.question)}
                            </span>
                          </div>
                        </AccordionTrigger>
                        <AccordionContent className="px-5 py-4 text-base text-muted-foreground bg-background">
                          <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.2 }}
                          >
                            {highlightText(item.answer)}
                          </motion.div>
                        </AccordionContent>
                      </AccordionItem>
                    </motion.div>
                  ))}
                </Accordion>
              </motion.div>
            ) : (
              <motion.div
                key="no-results"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.3 }}
                className="text-center py-12"
              >
                <motion.div
                  animate={{
                    scale: [1, 1.1, 1],
                    rotate: [0, 5, 0, -5, 0],
                  }}
                  transition={{ duration: 2, repeat: Number.POSITIVE_INFINITY }}
                  className="inline-block mb-4"
                >
                  <HelpCircle className="h-12 w-12 text-muted-foreground mx-auto" />
                </motion.div>
                <p className="text-center text-base text-muted-foreground mb-4">
                  No matching FAQs found. Please try a different search term.
                </p>
                <motion.button
                  onClick={() => setSearchTerm("")}
                  className="text-primary hover:underline"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  Clear search and show all FAQs
                </motion.button>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </div>
    </section>
  )
}

